markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "åšä¸€æ¡å¿«ä¹çš„å°å’¸é±¼ï¼Œä»»é£å¹é›¨æ‰“ï¼Œåæ­£å†…å¤–å·²ç»å¹²é€äº†ğŸ˜€"
markdown: rdiscount
rdiscount:
    extensions:
      - generate_toc
      - footnotes
      - smart 
    toc_token: "@TOC"

author: "wangkai"
atom-baseurl: "https://kaycool.github.io/"
disqus: "gopherwood"

excerpt_separator: "<!--more-->"



navigations:
  - title: Archive
    class: fa fa-list-ul
    href:  archive.html
  - title: Tags
    class: fa fa-tags
    href:  tags.html
  - title: About
    class: fa fa-user
    href:  about.html
  - title: Subscribe
    class: fa fa-rss
    href:  atom.xml

#social
qq: "http://wpa.qq.com/msgrd?v=3&uin=1316017265&site=qq&menu=yes"
weibo: ""
wechat: "wk15156276550"
linkedin: "https://www.linkedin.com/in/%E5%87%AF-%E6%B1%AA-1082a8116/"
github: "https://github.com/kaycool"


siteurl: "https://kaycool.github.io/"
